% make plots of velocity distribution for all three models. Requires data
% generated by the three scripts 'vDist_*'.

clear all; close all;

load('par','v_max')

data = {'data_nasch_vdist','data_acc_vdist','data_fsl_vdist'};
filenms = {'plot_vdist_nasch','plot_vdist_acc','plot_vdist_fsl'};

fSze1 = 20;
fSze2 = 14;

xSize = 15;
ySize = 10;
xLeft = (21-xSize)/2; yTop = (30-ySize)/2;
pos = {[0 ySize],[xSize ySize],[0 0]};

colmap = jet(v_max+2);
colmap = [[1 0 0]; colmap((end-1):(-1):3,:); [0 0 1]];

for k=1:length(data)
    load(data{k})
    v_dist = v_dist./1000;
    figure(k);
    colormap(colmap);
    set(gcf,'PaperUnits','centimeters')
    set(gcf,'Units','centimeters')
    area(c,v_dist);
    grid on;
    set(gca,'layer','top');
    set(gca,'FontSize',fSze2);
    xlabel('density \it{c}','fontSize',fSze1);
    ylabel('velocity distribution','fontSize',fSze1);
    l = legend('v = 0','v = 1','v = 2','v = 3','v = 4','v = 5','Location','NorthWest');
    set(l,'fontSize',fSze2);
    set(gca,'XTick',0:0.1:1)
    set(gcf,'PaperPosition',[xLeft yTop xSize ySize])
    set(gcf,'Position',[pos{k}(1) pos{k}(2) xSize ySize])
    print('-depsc', filenms{k})
end
